# Generated by Django 4.1.1 on 2022-12-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpicture',
            name='profile_picture',
            field=models.ImageField(default='pictures/default.jpeg', upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='user',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to=settings.AUTH_USER_MODEL),
        ),
    ]
