# Generated by Django 4.1.1 on 2022-12-09 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_userpicture_profile_picture_alter_userpicture_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userpicture',
            name='patreon_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpicture',
            name='paypal_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpicture',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpicture',
            name='profile_picture',
            field=models.ImageField(default='pictures/default.jpeg', upload_to='pictures'),
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.ImageField(default='pictures/default.jpeg', upload_to='creations')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(max_length=5)),
                ('download_count', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('tags', models.ManyToManyField(blank=True, to='api.tag')),
                ('user', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('date', models.DateTimeField()),
                ('commenting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creation')),
            ],
        ),
        migrations.AddField(
            model_name='userpicture',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.country'),
        ),
    ]
